apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-counter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit-counter
  template:
    metadata:
      labels:
        app: visit-counter
    spec:
      containers:
      - name: visit-counter
        image: m1guelch/visit-counter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: visit-counter-storage
          mountPath: /data
        env:
        - name: DB_PATH
          value: "/data/visits.db"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: visit-counter-storage
        persistentVolumeClaim:
          claimName: visit-counter-pvc
