apiVersion: v1
kind: Service
metadata:
  name: visit-counter-service
spec:
  type: NodePort
  selector:
    app: visit-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
