---
- name: Instalar dependencias
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes

- name: Descargar e instalar K3s
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Esperar a que K3s esté listo
  shell: |
    kubectl get nodes
  register: k3s_check
  retries: 10
  delay: 5
  until: k3s_check.rc == 0

- name: Copiar kubeconfig al usuario actual
  become: true
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Reemplazar localhost por IP pública en kubeconfig
  become: true
  replace:
    path: /home/{{ ansible_user }}/.kube/config
    regexp: '127\.0\.0\.1'
    replace: '{{ hostvars[inventory_hostname].ansible_host }}'
