---
- name: (1/15) Update system and upgrade packages
  apt:
    update_cache: true
    upgrade: dist

- name: (2/15) Install required packages
  apt:
    name:
      - curl
      - wget
      - bash-completion
      - git
    state: present

- name: (3/15) Install Docker dependencies
  apt:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: (4/15) Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: (5/15) Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: (6/15) Install Docker Engine and Docker compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: (7/15) Enable and start Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: (8/15) Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
