---
- name: (3/6) Ensure kubeconfig is set for the user
  shell: |
    export KUBECONFIG=/home/{{ ansible_user }}/.kube/config
    kubectl get nodes
  register: k3s_status
  changed_when: false

- name: (4/6) Apply all K8s manifests to run the app
  shell: |
    export KUBECONFIG=/home/{{ ansible_user }}/.kube/config
    kubectl apply -f .
  args:
    chdir: /home/{{ ansible_user }}/pasir/k8s
  become: true
  become_user: "{{ ansible_user }}"

- name: (5/6) Get K8s resources
  command: kubectl get all -A
  register: kubectl_get_all

- name: (6/6) Show K8s resources
  debug:
    var: kubectl_get_all.stdout_lines
