services:

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "30090:80"
      - "30091:81"
      - "30092:443"
    networks:
      - npm_net
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: npm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: npm_password
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm_password
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - npm_net

networks:
  npm_net:
    driver: bridge
